### ISSUE TITLE
Error OSError: No such file as /dataset/ukdale.h5

### ISSUE THREAD

**Issue by saimunur** [BHafsa/DNN-NILM-template#1]
run saed_model_evaluation
Started training for  SAED
Joint training for  SAED
............... Loading Data for training ...................
Loading data for  ukdale  dataset
Traceback (most recent call last):
  File "experiment.py", line 46, in <module>
    template.run_template(EXPERIMENT_NAME,
  File "/home/user/miniconda/lib/python3.8/site-packages/deep_nilmtk/utils/templates/experiment_template.py", line 71, in run_template
    _ = setup(self.experiment, experiment_name=experiment_name,
  File "/home/user/miniconda/lib/python3.8/site-packages/deep_nilmtk/utils/experiment_starter.py", line 36, in setup
    api_res = API(experiment)
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/api.py", line 46, in __init__
    self.experiment()
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/api.py", line 91, in experiment
    self.train_jointly(clf,d)            
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/api.py", line 208, in train_jointly
    train=DataSet(d[dataset]['path'])
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/dataset.py", line 45, in __init__
    self.import_metadata(get_datastore(filename, format))
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/utils.py", line 323, in get_datastore
    return HDFDataStore(filename, mode)
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/docinherit.py", line 53, in f
    return self.mthd(obj, *args, **kwargs)
  File "/home/user/miniconda/lib/python3.8/site-packages/nilmtk/datastore/hdfdatastore.py", line 18, in __init__
    raise IOError("No such file as " + filename)
OSError: No such file as /dataset/ukdale.h5
Closing remaining open files:/tmp/nilmtk-guod8xa5.h5...done

I already copied the ukdale dataset in dataset folder but still getting the error. Please help.

**Comment by BHafsa** [comment]
I believe that you copied the dataset after building the docker image. The following command may solve your problem without re-building the image: 
```
docker run --gpus 'all' --name exp_exec experiment_setup -v ~/dataset:/dataset
```
